"🤖 Android":
- changed-files:
  - any-glob-to-any-file: ['microGallery_Android/**']
"🍎 iOS":
- changed-files:
  - any-glob-to-any-file: ['microGallery_iOS/**']
"🫏 KMP":
- changed-files:
  - any-glob-to-any-file: ['microGallery_KMP/**']
